name: Daily Commit Workflow

on:
  schedule:
    - cron: '15 8 * * *'  # 8:05 AM UTC = 1:35 PM IST
  workflow_dispatch:      # Allows manual "Run workflow" button

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Step by 23f2003824@ds.study.iitm.ac.in - Make a Dummy Change
        run: |
          echo "Commit made on $(date)" >> daily_commit_log.txt

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit Changes
        run: |
          git add daily_commit_log.txt
          git commit -m "Automated daily commit on $(date)" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
